#logging:
#    level:
#        org:
#            hibernate:
#                SQL: DEBUG
#                stat: DEBUG
server:
    port: 8080
spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/music_application
      username: root
      password: admin

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
#              generate_statistics: true
              format_sql: true
        show-sql: true
        hibernate:
          ddl-auto: update

